---
title: "Historical collections as baseline for assessing the extent of the pollinator crisis"
author: "I. Bartomeus1, J. Stavert2, D. Ward2,3, O. Aguado4"
csl: data/philb_style.xml
output:
  html_document: default
bibliography: data/references.xml
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#req: 6000 words max. inc ref's 3 figures
#deadline: 1st April
```

[Historical collections or museum collections?]()

*Affiliations:*
1 Estación Biológica de Doñana (EBD-CSIC), Avda. Américo Vespucio 26, Isla de la Cartuja, E-41092 Sevilla, Spain   
2 Centre for Biodiversity and Biosecurity, School of Biological Sciences, The University of Auckland, Auckland, New Zealand
3 Landcare Research, Auckland, New Zealand
4 Andrena Soluciones  
*Correspondence: nacho.bartomeus@gmail.com  

*Author contributions*: IB wrote the initial draft. DW and OA provided data. IB and JS analyzed the data. All authors contributed to writting the manuscript.

#Abstract  

There is increasing concern about the decline of pollinators worldwide. However, despite reports that pollinator declines are widespread, data are scarce and often geographically and taxonomically biased. These biases limit robust inference about any potential “pollinator crisis”. Analysis of historical time series data is the most direct approach for assessing species declines, but long term monitoring programs targeting pollinators are scarce. However, non-structured and often opportunistic historical data collections are more frequently available. In many instances, these data provide the only source of historical information serving as a baseline for identifying pollinator declines. Specimens historically collected and preserved in museums can provide information on where and when species were collected, in addition to other ecological information (e.g., historical species interactions and morphological traits). Here, we provide a synthesis of how researchers have used museum specimens to compare historical occurrences with current patterns to identify long-term changes in biodiversity, species abundances, body size and even pollination services. Despite recent advances, we show that information on the status and trends of most pollinators is absent, and that the lack of collection record data digitization is a key bottleneck, impeding progress in this field. We identify opportunities and limitations to progress in assessing pollinator declines at a global scale. Further, we demonstrate various approaches to analyzing museum collection data by providing two contrasting case studies from distinct geographical regions (New Zealand and Spain) for which long-term pollinator declines have never been assessed. We show that for both regions, winners and loser species emerge despite a lack of significant richness changes over time. There is immense potential for museum specimens to play a central role in assessing the global pollination crisis extent, but we must make these data feely accessible to researchers.


#Introduction  

Animal pollinators are a critical component of both natural and agricultural ecosystems worldwide, given their role in plant reproduction [@Ollerton2011] and food security [@Klein2007]. As with many other taxa, pollinators are vulnerable to a range of anthropogenic disturbances, which can cause local and regional population declines or even extinctions. The vulnerability of pollinators was identified several decades ago, and was popularized in 1996 by the influential book “the forgotten pollinators” [@Buchmann1996]. However, early accounts were somewhat anecdotal, given the lack of data on pollinator populations at that time. These initial claims triggered the first efforts to assess the problem, including the formation of a US National Academy of Science (NAS) panel in 2006, which was commissioned to assess the extent of pollinator declines. The NAS report concluded that “For most pollinator species […] the paucity of long-term population data and the incomplete knowledge of even basic taxonomy and ecology make definitive assessment of status exceedingly difficult” [@NationalResearchCouncil2007]. Since then, studies on pollinator responses to various global change drivers have multiplied rapidly. Researchers have now developed strong consensus that disturbances such as habitat destruction, land-use intensification, chemical exposure, exotic species and climate change are causing pollinator declines, and often act synergistically [@Goulson2015; @Potts2010]. Yet, the current status and population trends of most pollinator species worldwide remain unknown. For example, a recent IUCN report concluded that even for Europe’s comparatively well-studied bee fauna, > 55% of bee species fell into the “Data Deficient” category [@Nieto2014]. For countries outside of Europe and the US, data on pollinator populations is almost non-existent.

One of the main barriers to identifying trends in pollinator populations is that pollinators are incredibly diverse and include bees, flies, butterflies, beetles, birds, bats and even lizards [@Winfree2011]. All this groups of pollinators are often highly mobile, short-lived and small, difficulting the monitoring of its poplations. Bees are generally regarded as the most important pollinator group due to their abundance, pollination efficiency and widespread distribution [@Ollerton2017]. However, bees are also diverse, with more than 20,000 species currently described worldwide [@Archer2014], and often require expert taxonomists for identification. Furthermore, the uneven distribution of researchers [@Martin2012] has also resulted in geographical biases in bee decline research, as well as taxonomic biases toward species that are easier to identify, such as bumblebees [@Archer2014; @DePalma2016]. 

One solution to overcoming these barriers has been to use space-for-time substitutions, where researchers compare pollinator populations across environmental gradients. Despite critiques on the robustness of this approach [@Franca2016; @DePalma2018], this is the most extensive source of data on pollinator populations currently available. For example, in Europe, researchers have recently estimated bee richness declines for every country using predictions generated from models using pollinator associations to different land uses [@DePalma2017]. A second promising method is assessing data collected in pollinator monitoring programs, which are often driven by citizen scientists. This approach was inspired by successful butterfly monitoring programs [@vanSwaay2008] and is currently being extended to other pollinator taxa. However, these programs require significant time to generate long-term datasets and cannot reveal anything about historic pollinator populations. Finally, the most practical approach for assessing long-term pollinator population trends is to use the available historical information on species occurrences deposited in museum specimen collection data [e.g., @Bartomeus2013a]. 

In this review we first assess current evidence for diversity declines and present a road map outlining a strategy for using museum data to fill current knowledge gaps. We highlight the major technical difficulties involved in using museum collection data and demonstrate how to approach analysis of different types for museum collection data to identify long-term trends in pollinator populations. Finaly, we highlight the need to move beyond simple diversity descriptors and unleash the power of historical data to assess also species interactions, ecosyetm functioning and evolutionary changes along time. 

#Current evidence on pollinatior declines    

At a global scale, current evidence of pollinator declines highly limited with most data restricted to the US and countries in Europe. It is unsurprising that most evidence of pollinator declines is biased towards developed western countries, which have also been subject to extensive anthropogenic disturbance. For example, in the UK and the Netherlands, a citizen science based study using both observations and museum collections detected strong declines for bee, hoverfly and flowering plant richness [@Biesmeijer2006]. However, it is important to note that even for these two countries, local estimates of pollinator richness are biased toward large cities and regions dominated by agriculture, and data is lacking for natural areas. Further exploration of this dataset revealed that for declining pollinator taxa, the trend has attenuated in recent decades [@Carvalheiro2013]. 

More detailed patterns for common bee species in the Netherlands, aslo using museum historical specimens, have shown simultaneous plant and pollinator declines [@Scheper2014]. Specifically, bee species with the strongest host plant preferences (i.e., specialists) displayed the strongest declines and thus, were most threatened with extinction. Although studies of local pollinator communities often detect richness declines, regional richness may remain relatively stable. For example, regional estimates for species richness changes in the eastern US show moderate declines [@Bartomeus2013a] and very few regional extinctions [@Colla2012]. A pattern also found in the UK [@Ollerton2014]. The US findings are in stark contrast with the widespread local extinctions reported by Burkle [@Burkle2013], who compared historical observations of bee occurrence in a large forested ecosystem with remaining forest remnants. However, it is important to note that this study focused on habitat remnants and did not take into account opportunistic bee species that use novel land-use types (@Collado2018). In any case, there is strong concordance between local extinctions and regional declines [@Bartomeus2013c], suggesting that local extinctions are indicators of regional population declines.

As with bees, studies on changes in species richness for other pollinator taxa is scarce and geographically restricted. Generally speaking, reported declines for bumblebees have been more severe. For example, declines of up to 18% in local bumble richness have been reported for Belgium and the Netherlands [@Carvalheiro2013]. In other parts of Europe local richness declines range from 5% for Great Britain [@Carvalheiro2013] to 42% for Denmark [@Dupont2011]. In the USA, reported bumble decline are also severe with estimates ranging between 25% [@Grixti2009] and 30% [@Bartomeus2013a]. For butterflies, the only evidence of richness declines come from Europe. For example, butterfly species richness has declined substantially in the Netherlands and Belgium since the 1950’s, although in Great Britain declines have been less severe [@Carvalheiro2013]. Another study in Belgium showed that richness declines have been more severe (approximately 30%), although this study exampled changes in richness over a longer time period (early 1900’s to 2000) [@Maes2001]. In parts of Germany, declines in local butterfly richness have been even more severe, with declines of up to 70% reported [@Wenzel2006]. There are very few studies on changes in hoverfly species richness and are once again restricted to Europe. In Belgium, Great Britain and the Netherlands, changes in hoverfly richness have been modest [@Carvalheiro2013]. In the Netherlands, moderate increases in hoverfly species richness have been shown, whereas in Great Britain no significant directional changes were detected [@Biesmeijer2006]. Furthermore, directionality (richness increases or decreases) varies depending on the time period that richness changes have been assessed. For example, hoverfly richness decreased in Belgium decreased by approximately 6% from 1950-69 compared with 1970-80, but increased by approximately 10% between 1970-89 and 1990-2009 [@Carvalheiro2013].

Outside of Europe and the US there are no studies on pollinator declines using historical records. In Fig 1 we show a comparision of bee species richness per area (a), bee species richness changes (b), syrphid species richness changes (c) and butterfly species richness changes (d) to highlight the little coverage that we have globally. See raw data at Sup Mat 1. For other parts of the world there are only species-specific examples of historical losses (e.g., Bombus dalbhomi; @Morales2013) [South Africa: Pauw, maybe with plants… . However,Peter Keil flies? Moths? Butterflies!]()


Figure 1: Global map showing a) bee species richness per area (Data from www.discoverlife.org). This is calculated as the residuals of the log-log regresion between bee richness and country size to account for the species-area relationships. We show mean local bee (b), syrphid (c) and butterflies (d) richness percent change in the last century. Warmer colors indicate steeper declines observed. Countries without available data are coloured in white. Note that some African countries may have incomplete faunas listed and that Alaska is included with US values. 

#How to use historical records vouchered in museum specimens to fill the gaps.

As evidenced in Fig 1, we lack specific estimates for most of the world countries and histrical data vouchered in museums may be the only change to fill those gaps. 

The core aim of museums is to conserve and curate collections. Thus, they serve as a precious repository for specimens, and at the same time often ensure higher quality taxonomic identification. Yet, the major bottleneck for researchers wanting to use these data is the lack of digitization. Digitizing old collection specimens is not a trivial task and requires expertise to (i) ensure proper taxonomic identification [@Meier2004; @Huber1998; @Thomson2018], (ii) geo-locate the coordinates of collection events [@ref and software] and (iii) store the data in a properly curated database [@Hart2016]. Undertaking this process for tens or hundreds of thousands of museum collections specimens can be a daunting task and requires specialized personnel. While some tasks can only be undertaken by people with specialist skills (e.g., taxonomists), new technologies and citizen science can speed up the collection digitization process. High resolution photos of specimens and associated labels can be uploaded to the internet, where the job of image transcription can be distributed across hundreds or thousands of volunteers (e.g. https://www.zooniverse.org/). In addition, new algorithms have been created that allow location geo-referencing based on vernacular names [@ref geonames, geoparser and opencage]. However, achieving all this goals needs propoer funding [@Wiggins1991].

Where digitization has been completed, the data provide a rich source of information and have allowed the assessment of the current statuses and long-term trends in pollinator populations [e.g., @Bartomeus2013a; @Scheper2014; @Young2017]. This is despite the fact that museum collections often have a number of biases. This biases includes the unknown sampling effort that was employed or the personal interests and curatorial techniques of collectors. For example, collectors tend to target rare or unusual over common taxa, discard damaged individuals or only accession a certain number of individuals. In addition, the opportunistic nature of museum collections often imply an spatial bias where areas have been undersampled, or where samples are biased towards easily collected localities (e.g. near towns/cities and/or along roadsides) and that information is often restricted only to the presence of a species (i.e. there is no information on where a species is absent). Given adequate sample sizes, most of this biases can be accounted for with propoer statistical data anslysis [e.g., @Bartomeus2013a; @Keil2011; @Pearce2006]. Nevertheless, in many cases, museum collections are the only data we have to reconstruct the past.

#The way forward: Prioritizing the low hanging fruit.   

As we have seen, there is a paucity of countries for which museum data is available (Fig 1), and hence can be used as baseline for assessing pollinator population declines. While ideally, one would aim to digitize all museum records in the world, this is unlikely to happen in the near future due mainly to funding constraints. Here we illustrate how this can be prioritized and optimized to encourage independent researchers to assess declines in its own country.

GBIF (https://www.gbif.org/) is a central repository centralizing occurrence data from around the globe. Much of this data comes from museums, collections and goverment research institutes, but it integrates several other sources. Alongside the popular statistical language R [@RCoreTeam2017], GBIF can be directly queried into your computer [@Chamberlain2014] and data availability checked for your region of interest. In Figure 2 we show the number of modern and historical bee records already available per country. While for some countries like UK and US the numbers are high in both axes, and hence, data can be potentially analyzed without further data collection efforts, most countries fall short in one or both of the axes. Hence, for countries with large number of recent records, researchers should prioritize the digitalization of old material to conduct their analysis. On the contrary, for countries with large number of historical records, re-surveys should be organized [e.g., @Cameron2011]. Interestingly, we show that >100 countries have less than 1000 records, making them unlikely candidates to study, but countries like X or X… Also note that historical records are not always in local museums, but many EU and US museums contain large collection of exotic pollinators. Similar exploratry analysis can be easely done for other taxa.
  

Figure 2. The number of bee occurrences pre 1980 and post 1980 in GBIF. Upper right quadrat are well covered countries, upper left quadrat are countries that need resurvey of old sites. Lower right are sites which needs to dig museum records and lower left are countries with very little data available. We highlight a few representative examples.

Once museum collection datasets are made available, researchers need to gauge any potential biases in the data. We explore this process with two contrasting and ilustrative examples from Spain and New Zealand. In the Spanish dataset, most of the data comes from a few specific locations and was collected by the same team of people. In this case, we contacted the original collectors to define their sampling protocols. We then resurveyed the same sites using the same protocols 20 years later. Conversely, the New Zealand dataset includes a wide suite of collectors and collection locations, but luckely, tehere is no obvious bias in the geographical and taxonomic coverage through time. For these case studies, we provide annotated R scripts to analyse the different kinds of data (e.g. for Spain and New Zealand, as described above). Essentially, these different analytical approaches allow us to reveal long-term trends in pollinator populations for regions with contrasting sampling histories. We hope this resource will encourage researchers to analyze data for regions where there is little current information on pollinator declines.

#Case study one: Spain  

Spain provides an interesting study system because its natural habitats have been transformed extensively by humans, but land-use is not as intensive as in many other European countries. In addition, Spain is a bee diversity hotspot (Fig 1) and maintains a relatively heterogeneous landscape. Spain has already digitalized a large amount of occurrence data for both historical and recent periods (Fig 2). However, visual inspection of the data reveals that the data is clustered around a few localities. Further, historic records do not spatially match recent records, making them difficult to compare. For this dataset, most of the historical records are located around Valladolid and were collected by Enrique Asensio and his collaborators. There has been no recent sampling of bees in this area. However, we found that Enrique systematically sampled seven locations and that there was additional data available at the “Museo de Historia Nacional” and other minor collections. Digitization of these records, along with a re-survey of these locations provided an excellent dataset for a before and after comparison of bee communities at these locations. [from Darren: Has there been any changes in the land use between the two periods?]

In brief, we check sampling completeness at both time periods, and compare the species richness level of each site before 1980 and after 1980 with a paired t-test. We show that overall there is no no difference in species richness (p > 0.05). However, ... show a steep decline… and groups like nomadas, tyreus, prosopis and teralonias are completely extirpated (appendix?). [from Darren: Any information on these groups. Are the specialists species, or more sensitive to land change?].


Figure 3. Rarefied richness at the 5 plots... need to work more on the raw data.   

#Case study two: New Zealand

In contrast to Spain, New Zealand is an isolated oceanic archipelago, with a distinctive pollinator biota and a unique history of human occupation. Much of New Zealand’s pollinator fauna is also relatively depauperate. For example, New Zealand has only 27 species of native bees [@Donovan2007], which is a fraction of nearby Australia’s c. 1600 species [#@ref]. However, New Zealand has a surprisingly high diversity of fly (Diptera) pollinators, which are important pollinators in many ecosystems [@Newstrom2005]. Thus, New Zealand provides a unique system to study long-term changes in pollinator communities, and is unlike continental Europe and the US, which have been the focus of an overwhelming majority of pollinator decline studies.

In global terms, human colonisation of New Zealand was relatively recent (c. 740 y) [@Wilmshurst2008]. Before human arrival, New Zealand was predominately forested, but has since been dramatically altered by people. Early Māori settlers cleared forests by burning and more recently, European colonists cleared large tracts of remaining forests and drained low-lying wetlands for agriculture, mostly before 1900 [@Perry2014]. Therefore, human activity likely affected pollinator communities in New Zealand long before surveys and collections began. Nevertheless, we can use museum records to identify trends in pollinator communities during New Zealand’s more recent history.

We used New Zealand bee collection records gathered from multiple sources, including university, research institute, museum and private collections. Collection records from the New Zealand Arthropod Collection (NZAC) are freely available online (https://scd.landcareresearch.co.nz/). Fly pollinator data was obtained from six participating New Zealand museums [need to list in the acknowledgments]() and covers two families (Calliphoridae and Syrphidae) that contain important fly pollinators. Collections for the bee and fly datasets span over 100 years (early 1900s to late 2000s).

We follow Bartomeus et al. 2013a protocol to analysze this data. First, we filtered our original datasets so that data used for analyses only included independent collection events. To do this, we removed specimens collected at the same location, on the same date, and by the same collector. We found our data had reasonable coverage across time periods, although there was a peak in collection occurrences from 1960-1980. We accounted for differences in collection effort through binning collection records by time so that each bin had a similar number of records but a different number of years. We then estimated richness for each time period bin by rarefying all bins to an equal number of specimens and calculated the mean species richness ±SE for each bin. Finally, we estimated the significance of change in richness using a permutation test that randomly reordered time periods and calculated the correlation between time period and species richness. Thus, reported P-values were the proportion of permutations that had higher or lower correlations compared to the correlation between richness and the actual chronological time period sequence.

Second, to determine if the probability of finding a species in the collection changed over time, we used a general linear model with a binomial distribution and a logit link. For species that showed overdispersion, we used a quasi-binomial distribution. Further, we only included species in this analysis for which we had 30 or more records. To account for differences in sampling effort between years, we weighted each year by the total number of samples collected in that year.

We found that rarefied richness for both native and exotic bees increased overtime, but these trends were non-significant (P-values for both groups > 0.05). In contrast, native fly richness declined, whereas exotic fly richness increased, although results for these groups were also non-significant (P-values for both groups > 0.05). Note that rarefied richness is sensitive to species evenness, so increases in rarefied richness over time may actually indicate increased species evenness.


Figure 4. Changes in rarefied species richness for different pollinator groups in New Zealand over time. All trends were non-significant (α = 0.05).

However, at the species level, we found that 10 out of 27 bee species increased in relative abundance over time (nine native and one exotic) and three bee species declined in relative abundance (one native and two exotic) (Fig 3). Interestingly, the two exotic bee species that declined in relative abundance were both in the genus Bombus, intentionally introduced into New Zealand for the pollination of crops. Native bees that increased in relative abundance were mostly from the genus Leioproctus. Only two out of 14 fly species increased in relative abundance, both of which were exotic, whereas four species decreased in abundance (three native and one exotic). Native flies that decreased in relative abundance were all Syrphidae in the genus Helophilus.


Figure 5. Model estimated changes (± 1 SE) in the relative occurrence frequency for different New Zealand bee and fly species in museum collections over time.

#Beyond species occurrences  
 
A recent survey highlighted that more than 90% of the papers studying pollinator responses to land use change focused solely on richness and abundance descriptors [@Winfree2011]. But in addition to local (alpha) diversity and regional (gamma) diversity, we need to understand changes in turnover between sites (beta diversity). Environmental changes often results in a few species as “winners” and many species becoming “losers” [@Bartomeus2013b]. Identifying winners and losers is critical as the few winner species are often exotic and represent a subset of traits that facilitate survival in highly modified environments [@Stavert2018]. These changes can have important effects for pollination of native plant species and crops. 

But museum specimen collection can provide much more information besides species occurrence records, and such information is important to capture when digitizing collections. This is specifically relevant to identify mechanisms of decline and adaptation. For example, one particularly important source of information is the date the specimen was collected, which allows the tracking of phenological advances congruent with contemporary climate change [@Bartomeus2011]. In addition, museum labels on pollinator specimens often include information about the host plant on which the specimen was collected. This information is precious to understand past and present species interactions [@Tylianakis2008]. Even when the host plant is not noted, bee specimens often contain pollen loads trapped in the hairs, making possible to reconstruct past visitation events [@Kleijn2008]. Finally, museum specimens can be measured to track evolutionary changes by measuring specific specimen traits. This has been already explored to show tongue length [@Miller-Struttmann2015] and body size [@Oliveira2016] shrinkage with climate and land use change.


#Conclucions

As illustrated in our examples, unleashing the power of museum collection data to answer pressing questions is at our hands, but requires the coordinated effort of many actors. Using two case studies, we show that collaboration with both museum curators and ecologists is key to adequately understanding the data and treating it appropriately. Researchers and curators should aim to make digitalized data readily available and easy to share. Centralization of regional and national museum data in existing global platforms such as GBIF would facilitate free and widespread access. However, specific datasets can also be stored in different webpages or database repositories (e.g. Universities and museum webpages, Dryad) as far as they are well documented and can be easely retrived and combined with other datasets using open science tools [e.g., @Dallas2016].

We also need to revolutionize the way that researchers collaborate with museums, which should start with fostering healthy bidirectional relationships. For instance, ecological researchers collect massive amounts of specimens, but these are often inappropriately vouchered (@Packer2018; @Wheeler2003), rendering them less useful for future research. To improve this, strong communication between museums and researchers is required, but this will only be achieved if there is not adequate funding, and recognition that accurate data recording and long-term preservation are critical for research [@Ward2015].

Ultimately, to identify global trends in pollinator declines we require robust data, collected from diverse geographic regions. Further, it is crucial that data are analysed appropriately. This requires researches to identify biases in the data and fill  taxonomic and geographic gaps in knowledge of pollinators status where possible. We need to place increased emphasis on quantifying pollinator declines in regions outside of the US and Europe and for pollinator groups other than bees. For the US and Europe there have been few regional bee extinctions [@Ollerton2014; @Bartomeus2013a], but in disturbed ecosystems declines are widespread [@DePalma2017; @Bartomeus2013a; @Biesmeijer2006]. For most other pollinator taxa and regions throughout the world we know almost nothing. Moving forward, the first step for many taxa will be to identify and describe species. Only then can we begin to document declines.

#Acknowledgements  

IB was funded by FBBVA project. DW was funded through Landcare Research within the Characterising New Zealand’s Land Biota Portfolio. We thank E. Asensio for sharing his historical data and knowledge. We thank Curro Molina, Patrick McQuinn, and Crona McMonagle for data entry. Madrid museum of Historia Natural and ITACyL for access to historical collections. We also thank Barry Donovan for providing New Zealand bee collection records and Carola Warner for entering the New Zealand data.

#References