---
title: "Untitled"
author: "I. Bartomeus"
date: "26/03/2018"
output: html_document
---

To Do:

- check formating rules (words in abstract, main body, etc...)
- correct fig1 for country size?
- Species declines in % for different taxa... what to do?
- for NZ species abundance analysis - should data be split by exotic/native first?
- think on gbif plot...
- Spain.
- Refs -> e.g. not showing up in references in the final doc??


#refs clarifications

@Ollerton2011 -> Ollerton winfree and tarrant Oikos, I think 2012.
@Buchman1996 -> http://www.worldcat.org/title/forgotten-pollinators/oclc/34077459
@NAS -> @National2007 https://www.nap.edu/catalog/11761/status-of-pollinators-in-north-america
@Winfree2011 -> Winfree bartomeus Cariveau ARES
@PickeringAscher -> @Ascher2015 Ascher J.S., Pickering J. (2015) Discover Life bee species guide and world checklist (Hymenoptera: Apoidea: Anthophila). www.discoverlife.org
@Martinetal2012 -> @Martin2012: https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/110154?journalCode=fron
@Archer -> @Archer2014: https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1600-0706.2013.00949.x
@França: França, Filipe, et al. "Do space‐for‐time assessments underestimate the impacts of logging on tropical biodiversity? An Amazonian case study using dung beetles." Journal of Applied Ecology 53.4 (2016): 1098-1105.
@DePalma2018: De Palma, Adriana, et al. "Challenges With Inferring How Land-Use Affects Terrestrial Biodiversity: Study Design, Time, Space and Synthesis." Next Generation Biomonitoring 58 (2018): 163.
@DePalma2017 De Palma, Adriana, et al. "Dimensions of biodiversity loss: Spatial mismatch in land‐use impacts on species, functional and phylogenetic diversity of European bees." Diversity and Distributions 23.12 (2017): 1435-1446.
@DePalma2016: De Palma, Adriana, et al. "Predicting bee community responses to land-use changes: Effects of geographic and taxonomic biases." Scientific Reports 6 (2016): 31153.
@vanSwaay: -> @vanSwaay2008 van Swaay, Chris AM, et al. "Butterfly monitoring in Europe: methods, applications and perspectives." Biodiversity and Conservation 17.14 (2008): 3455-3469.
@Scheper2014. PNAS Museum specimens reveal loss of pollen host plants as key factor driving wild bee decline in The Netherlands
@pearce -> @Pearce2006 PEARCE, J. L. and BOYCE, M. S. (2006), Modelling distribution and abundance with presence‐only data. Journal of Applied Ecology, 43: 405-412. doi:10.1111/j.1365-2664.2005.01112.x
@young -> @Young2017 Are pollinating hawk moths declining in the Northeastern United States? An analysis of collection records
@helminth -> @Dallas2016 helminthR: an R interface to the London Natural History Museum's Host–Parasite Database
@keil -> @Keil2011 Biodiversity change is scale‐dependent: an example from Dutch and UK hoverflies (Diptera, Syrphidae)
P Keil, JC Biesmeijer, A Barendregt, M Reemer, WE Kunin
Ecography 34 (3), 392-401
@taxonomy1 -> @Meier2004
https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1523-1739.2004.00233.x
@taxonomy2 -> @Huber1998 Huber, J. T. "The importance of voucher specimens, with practical guidelines for preserving specimens of the major invertebrate phyla for identification." Journal of Natural History 32.3 (1998): 367-385.
@ref geonames, geoparser and opencage: those are likns to software.
@Hart -> @Hart2016 Ten simple rules for digital data storage. DOI: 10.7287/peerj.preprints.1448v1
@Collado2018: https://www.biorxiv.org/content/early/2018/03/08/278812
@Bartomeus_Winfree2013 -> @Bartomeus2013c F1000 https://f1000research.com/articles/2-146/v1
@Aizen -> @Morales2013 Morales, Carolina L., et al. "Rapid ecological replacement of a native bumble bee by invasive species." Frontiers in Ecology and the Environment 11.10 (2013): 529-534.
@Pauw: Reconstruction of historical pollination rates reveals linked declines of pollinators and plants
A Pauw, JA Hawkins - Oikos, 2011
Cited by 53 Related articles All 11 versions
@Bartomeus2011 PNAS phenology
@Tylianakis2010ELE Ecology letters It's 2008 sorry
@Kleijn -> @Kleijn2008 raemakers: https://www.ncbi.nlm.nih.gov/pubmed/18705369
@refAlaskaScience -> @Miller-Struttmann2015 http://www.sciencemag.org/content/349/6255/1541
@Oliveira -> @Oliveira2016 http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0148983
@R -> @RCoreTeam2017 just cite R
@rgbif -> @Chamberlain2014 https://cran.r-project.org/web/packages/rgbif/rgbif.pdf
@cameron2013 -> @Cameron2011 actually 2011 PNAS paper on bumblebees
@OllertonScience -> @Ollerton2014 Science paper on uk bee extinctions


#to add

@Greve2016 M. Greve, A.M. Lykke, C.W. Fagg, R.E. Gereau, G.P. Lewis, R. Marchant, A.R. Marshall, J. Ndayishimiye, J. Bogaert and J.-C. Svenning, Realising the potential of herbarium records for conservation biology, South African Journal of Botany, 105, (317)
@Lavoie2013 Claude Lavoie, Biological collections in an ever changing world: Herbaria as tools for biogeographical and environmental studies, Perspectives in Plant Ecology, Evolution and Systematics, 15, 1, (68)
X@Thomson -> @Thomson2018 Thomson SA, Pyle RL, Ahyong ST, Alonso-Zarazaga M, Ammirati J, Araya JF, et al. (2018) Taxonomy based on science is necessary for global conservation. PLoS Biol 16(3): e2005075. https://doi.org/10.1371/journal.pbio.2005075
X@brief1: -> @Wiggins1991 https://biologicalsurvey.ca/public/Bsc/Controller/Page/briefs/importance.pdf THE IMPORTANCE OF RESEARCH COLLECTIONS OF TERRESTRIAL ARTHROPODS
X@brief2: -> @Wheeler2003 http://biologicalsurvey.ca/assets/file/43 The role of voucher specimens in validating faunistic and ecological research
X@Packer2018 Packer, L. , Monckton, S. K., Onuferko, T. M., Ferrari, R. R. and Didham, R. (2018), Validating taxonomic identifications in entomological research. Insect Conserv Divers, 11: 1-12. doi:10.1111/icad.12284

@Cox1983 Cox, Paul Alan. “Extinction of the Hawaiian Avifauna Resulted in a Change of Pollinators for the Ieie, Freycinetia Arborea.” Oikos, vol. 41, no. 2, 1983, pp. 195–199. JSTOR, JSTOR, www.jstor.org/stable/3544263.
@Robbirt2011 Robbirt, Karen M., et al. "Validation of biological collections as a source of phenological data for use in climate change studies: a case study with the orchid Ophrys sphegodes." Journal of Ecology 99.1 (2011): 235-241.
@Maebe2013 Maebe, K., Meeus, I., Maharramov, J. et al. Apidologie (2013) 44: 188. https://doi.org/10.1007/s13592-012-0170-9 Microsatellite analysis in museum samples reveals inbreeding before the regression of Bombus veteranus.
@Mikheyev2015 Museum samples reveal rapid evolution by wild honey bees exposed to a novel parasite







